/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fifaworldcup;

import com.mongodb.client.model.Filters;
import java.util.ArrayList;
import org.bson.conversions.Bson;

/**
 *
 * @author Utente
 */
public class AdvancedSearchFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdvancedSearchFrame
     */
    public AdvancedSearchFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        playerTextField = new javax.swing.JTextField();
        goalCheckBox = new javax.swing.JCheckBox();
        ownGoalCheckBox = new javax.swing.JCheckBox();
        yellowCardCheckBox = new javax.swing.JCheckBox();
        redCardCheckBox = new javax.swing.JCheckBox();
        redCardBySecYellCheckBox = new javax.swing.JCheckBox();
        jLabel37 = new javax.swing.JLabel();
        penaltyCheckBox = new javax.swing.JCheckBox();
        missPenaltyCheckBox = new javax.swing.JCheckBox();
        subInCheckBox = new javax.swing.JCheckBox();
        subOutCheckBox = new javax.swing.JCheckBox();
        positionComboBox = new javax.swing.JComboBox<>();
        lineUpComboBox = new javax.swing.JComboBox<>();
        shirtComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        coachTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        stadiumTextField = new javax.swing.JTextField();
        homeTeamTextField = new javax.swing.JTextField();
        assistant1TextField = new javax.swing.JTextField();
        yearComboBox = new javax.swing.JComboBox<>();
        homeGoalsComboBox = new javax.swing.JComboBox<>();
        halfTimeHomeComboBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        refereeTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        awayTeamTextField = new javax.swing.JTextField();
        assistant2TextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JFormattedTextField();
        stageComboBox = new javax.swing.JComboBox<>();
        awayComboBox = new javax.swing.JComboBox<>();
        halfTimeAwayComboBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        attendanceComboBox = new javax.swing.JComboBox<>();
        attendanceTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();

        setTitle("Advanced search");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Player"));

        jLabel31.setText("Name");

        jLabel33.setText("Shirt Num.");

        jLabel34.setText("Position");

        jLabel35.setText("Line-up");

        jLabel36.setText("Event");

        goalCheckBox.setText("Goal");

        ownGoalCheckBox.setText("Own goal");

        yellowCardCheckBox.setText("Yellow card");

        redCardCheckBox.setText("Red card");

        redCardBySecYellCheckBox.setText("Red card by");

        jLabel37.setText("second yellow");

        penaltyCheckBox.setText("Penalty");

        missPenaltyCheckBox.setText("Missed penalty");

        subInCheckBox.setText("Substitution in");

        subOutCheckBox.setText("Substitution out");

        positionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Goalkeeper", "Captain" }));

        lineUpComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Line-up", "Substitute" }));

        shirtComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerTextField)
                    .addComponent(subOutCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shirtComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(positionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subInCheckBox)
                            .addComponent(missPenaltyCheckBox)
                            .addComponent(yellowCardCheckBox)
                            .addComponent(ownGoalCheckBox)
                            .addComponent(goalCheckBox)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(redCardBySecYellCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(redCardCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jLabel37))
                                .addComponent(penaltyCheckBox, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lineUpComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(playerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(shirtComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(positionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(lineUpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(goalCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownGoalCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yellowCardCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redCardCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redCardBySecYellCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penaltyCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(missPenaltyCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subInCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subOutCheckBox))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Match"));

        jLabel22.setText("Year");

        jLabel23.setText("Country");

        jLabel24.setText("Stadium");

        jLabel25.setText("Home Team");

        jLabel26.setText("Home Goals");

        jLabel27.setText("Half-t. Home");

        jLabel28.setText("Coach");

        jLabel29.setText("Assistant 1");

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "1930", "1934", "1938", "1950", "1954", "1958", "1962", "1966", "1970", "1974", "1978", "1982", "1986", "1990", "1994", "1998", "2002", "2006", "2010", "2014" }));

        homeGoalsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        halfTimeHomeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assistant1TextField)
                            .addComponent(homeTeamTextField)
                            .addComponent(stadiumTextField)
                            .addComponent(countryTextField)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(coachTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(yearComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(homeGoalsComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(halfTimeHomeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(stadiumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(homeTeamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(homeGoalsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(halfTimeHomeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(coachTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(assistant1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("Date");

        jLabel14.setText("City");

        jLabel15.setText("Stage");

        jLabel16.setText("Away Team");

        jLabel17.setText("Away Goals");

        jLabel18.setText("Half-t. Away");

        jLabel19.setText("Referee");

        jLabel20.setText("Assistant 2");

        stageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Group A", "Group B", "Group C", "Group D", "Group E", "Group F", "Group G", "Group H", "Group 1", "Group 2", "Group 3", "Group 4", "Group 5", "Group 6", "Preliminary Round", "First Round", "Round of 16", "Quarter-finals", "Semi-finals", "Match for third place", "Final", " " }));

        awayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        halfTimeAwayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cityTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(awayTeamTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assistant2TextField)
                            .addComponent(dateTextField)
                            .addComponent(refereeTextField))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(stageComboBox, 0, 101, Short.MAX_VALUE)
                    .addComponent(awayComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(halfTimeAwayComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(stageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(awayTeamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(awayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(halfTimeAwayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(refereeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(assistant2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        jLabel3.setText("Attendance");

        attendanceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">=", "<=", "=" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attendanceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attendanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(attendanceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(attendanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        clearButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchButton.setText("Search");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
        ArrayList<Bson> matchFilters = new ArrayList<>();
        ArrayList<Bson> playerFilters = new ArrayList<>();
        String country = "";
        Bson query;
        if(!yearComboBox.getSelectedItem().equals("None")){
            query = Filters.eq("Year", yearComboBox.getSelectedItem());
            matchFilters.add(query);
        }
        country = countryTextField.getText();
        if(!country.equals("")){
            matchFilters.add(Filters.exists("Year"));
        }
        if(!dateTextField.getText().equals("")){
        query = Filters.eq("Datetime", dateTextField.getText());
        matchFilters.add(query);
        }
        if(!cityTextField.getText().equals("")){
        query = Filters.eq("City", cityTextField.getText());
        matchFilters.add(query);
        }
        if(!stadiumTextField.getText().equals("")){
        query = Filters.eq("Stadium", stadiumTextField.getText());
        matchFilters.add(query);
        }
        if(!homeTeamTextField.getText().equals("")){
        query = Filters.eq("Home Team Name", homeTeamTextField.getText());
        matchFilters.add(query);
        }
        if(!awayTeamTextField.getText().equals("")){
        query = Filters.eq("Away Team Name", awayTeamTextField.getText());
        matchFilters.add(query);
        }
        if(!coachTextField.getText().equals("")){
        query = Filters.regex("Coach Name", ".*"+coachTextField.getText()+ ".*","i");
        playerFilters.add(query);
        }
        if(!refereeTextField.getText().equals("")){
        query = Filters.eq("Referee", refereeTextField.getText());
        matchFilters.add(query);
        }
        if(!assistant1TextField.getText().equals("")){
        query = Filters.eq("Assistant 1", assistant1TextField.getText());
        matchFilters.add(query);
        }
        if(!assistant2TextField.getText().equals("")){
        query = Filters.eq("Assistant 2", assistant2TextField.getText());
        matchFilters.add(query);
        }
        if(!stageComboBox.getSelectedItem().equals("None")){
        query = Filters.eq("Stage", stageComboBox.getSelectedItem());
        matchFilters.add(query);
        }
        if(!homeGoalsComboBox.getSelectedItem().equals("None")){
        query = Filters.eq("Home Team Goals", homeGoalsComboBox.getSelectedItem());
        matchFilters.add(query);
        }
        if(!awayComboBox.getSelectedItem().equals("None")){
        query = Filters.eq("Away Team Goals", awayComboBox.getSelectedItem());
        matchFilters.add(query);
        }
        if(!halfTimeHomeComboBox.getSelectedItem().equals("None")){
        query = Filters.eq("Half-time Home Goals", halfTimeHomeComboBox.getSelectedItem());
        matchFilters.add(query);
        }
        if(!halfTimeAwayComboBox.getSelectedItem().equals("None")){
        query = Filters.eq("Half-time Away Team Goals", halfTimeAwayComboBox.getSelectedItem());
        matchFilters.add(query);
        }
        if (!attendanceTextField.getText().equals("")) {
            if (attendanceComboBox.getSelectedItem().equals(">="))
                matchFilters.add(Filters.gte("Attendance", Integer.parseInt(attendanceTextField.getText())));
            if (attendanceComboBox.getSelectedItem().equals("<="))
                matchFilters.add(Filters.lte("Attendance",Integer.parseInt(attendanceTextField.getText())));
            if (attendanceComboBox.getSelectedItem().equals("="))
                matchFilters.add(Filters.eq("Attendance",Integer.parseInt(attendanceTextField.getText())));
        }
        if(!playerTextField.getText().equals("")){
        query = Filters.regex("Player Name", ".*"+playerTextField.getText()+ ".*","i");
        playerFilters.add(query);
        }
        if(!shirtComboBox.getSelectedItem().equals("None")){
        query = Filters.eq("Shirt Number",shirtComboBox.getSelectedItem());
        playerFilters.add(query);
        }
        if(!positionComboBox.getSelectedItem().equals("None")){
            String item = (String) positionComboBox.getSelectedItem();
            if (item.equals("Goalkeeper")) {
                query = Filters.eq("Position", "GK");
                playerFilters.add(query);
            } else if (item.equals("Captain")) {
                query = Filters.eq("Position", "C");
                playerFilters.add(query);
            }
        }
        if(!lineUpComboBox.getSelectedItem().equals("None")){
            String item = (String) lineUpComboBox.getSelectedItem();
            if (item.equals("Line-up")) {
                query = Filters.eq("Line-up", "S");
                playerFilters.add(query);
            } else if (item.equals("Substitute")) {
                query = Filters.eq("Line-up", "N");
                playerFilters.add(query);
            }
        }
        if(goalCheckBox.isSelected()){
        query = Filters.regex("Event", ".*"+"G"+ ".*","i");
        playerFilters.add(query);
        }
        if(subInCheckBox.isSelected()){
        query = Filters.regex("Event", ".*"+"I"+ ".*","i");
        playerFilters.add(query);
        }
        if(ownGoalCheckBox.isSelected()){
        query = Filters.regex("Event", ".*"+"OG"+ ".*","i");
        playerFilters.add(query);
        }
        if(yellowCardCheckBox.isSelected()){
        query = Filters.regex("Event", ".*"+"Y"+ ".*","i");
        playerFilters.add(query);
        }
        if(redCardCheckBox.isSelected()){
        query = Filters.regex("Event", ".*"+"R"+ ".*","i");
        playerFilters.add(query);
        }
        if(redCardBySecYellCheckBox.isSelected()){
        query = Filters.regex("Event", ".*"+"SY"+ ".*","i");
        playerFilters.add(query);
        }
        if(penaltyCheckBox.isSelected()){
        query = Filters.regex("Event", ".*"+"P"+ ".*","i");
        playerFilters.add(query);
        }
        if(missPenaltyCheckBox.isSelected()){
        query = Filters.regex("Event", ".*"+"MP"+ ".*","i");
        playerFilters.add(query);
        }
        if(subOutCheckBox.isSelected()){
        query = Filters.regex("Event", ".*"+"O"+ ".*","i");
        playerFilters.add(query);
        }
        homeFrame.advancedSearch(matchFilters, playerFilters, country);
        homeFrame.toFront();
    }//GEN-LAST:event_searchButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        // TODO add your handling code here:
        assistant1TextField.setText("");
        assistant2TextField.setText("");
        attendanceComboBox.setSelectedIndex(0);
        attendanceTextField.setText("");
        awayComboBox.setSelectedIndex(0);
        awayTeamTextField.setText("");
        cityTextField.setText("");
        coachTextField.setText("");
        countryTextField.setText("");
        dateTextField.setText("");
        goalCheckBox.setSelected(false);
        halfTimeAwayComboBox.setSelectedIndex(0);
        halfTimeHomeComboBox.setSelectedIndex(0);
        homeGoalsComboBox.setSelectedIndex(0);
        homeTeamTextField.setText("");
        lineUpComboBox.setSelectedIndex(0);
        missPenaltyCheckBox.setSelected(false);
        ownGoalCheckBox.setSelected(false);
        penaltyCheckBox.setSelected(false);
        playerTextField.setText("");
        positionComboBox.setSelectedIndex(0);
        redCardBySecYellCheckBox.setSelected(false);
        redCardCheckBox.setSelected(false);
        refereeTextField.setText("");
        shirtComboBox.setSelectedIndex(0);
        stadiumTextField.setText("");
        stageComboBox.setSelectedIndex(0);
        subInCheckBox.setSelected(false);
        subOutCheckBox.setSelected(false);
        yearComboBox.setSelectedIndex(0);
        yellowCardCheckBox.setSelected(false);
    }//GEN-LAST:event_clearButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvancedSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvancedSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvancedSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvancedSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvancedSearchFrame().setVisible(true);
            }
        });
    }

    public void setHomeFrame(HomeFrame frame) {
        homeFrame = frame;
    }
    
    private HomeFrame homeFrame;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assistant1TextField;
    private javax.swing.JTextField assistant2TextField;
    private javax.swing.JComboBox<String> attendanceComboBox;
    private javax.swing.JTextField attendanceTextField;
    private javax.swing.JComboBox<String> awayComboBox;
    private javax.swing.JTextField awayTeamTextField;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField coachTextField;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JFormattedTextField dateTextField;
    private javax.swing.JCheckBox goalCheckBox;
    private javax.swing.JComboBox<String> halfTimeAwayComboBox;
    private javax.swing.JComboBox<String> halfTimeHomeComboBox;
    private javax.swing.JComboBox<String> homeGoalsComboBox;
    private javax.swing.JTextField homeTeamTextField;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> lineUpComboBox;
    private javax.swing.JCheckBox missPenaltyCheckBox;
    private javax.swing.JCheckBox ownGoalCheckBox;
    private javax.swing.JCheckBox penaltyCheckBox;
    private javax.swing.JTextField playerTextField;
    private javax.swing.JComboBox<String> positionComboBox;
    private javax.swing.JCheckBox redCardBySecYellCheckBox;
    private javax.swing.JCheckBox redCardCheckBox;
    private javax.swing.JTextField refereeTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> shirtComboBox;
    private javax.swing.JTextField stadiumTextField;
    private javax.swing.JComboBox<String> stageComboBox;
    private javax.swing.JCheckBox subInCheckBox;
    private javax.swing.JCheckBox subOutCheckBox;
    private javax.swing.JComboBox<String> yearComboBox;
    private javax.swing.JCheckBox yellowCardCheckBox;
    // End of variables declaration//GEN-END:variables
}
